### ISSUE TITLE
Problem using Monophase with Jekyll 4.2.0

### ISSUE THREAD

**Issue by andradeoromulo** [zivhub/monophase#1]
I'm really new to Jekyll, Ruby and Gems, so I don't know if this topic will make sense. Anyway, I created a new project with Jekyll and decided to use `Monophase` as the theme (by the way, thanks for sharing this beautiful minimalist theme). As I just installed Jekyll and its requirements, the project's `Gemfile` was configured to use Jekyll 4.2.0 (latest version with bug and optimization fixes). However, when I tried to run `bundle update`, I received this message:  
```
In Gemfile: 
     jekyll (~> 4.2.0)

    monophase was resolved to 0.1.0, which depends on
      jekyll (~> 3.9)
```
So I had to edit the `Gemfile` and downgrade Jekyll version, but is there a way to use its latest version tho? If not, wouldn't it be a good ideia to update `Monophase` to use the latest version?

Once again, thank you for this theme! :)

**Comment by lcvisser** [comment]
Just hypothesizing here, but [GitHub Pages uses Jekyll 3.9.0](https://pages.github.com/versions/), which may be why @zivhub  choose to depend on that version too.

**Comment by pentos9** [comment]
@andradeoromulo i have the same problem and fixed it by doing this: replace (gem "jekyll", "~> 4.2.0") with (gem "jekyll", "~> 3.9").just downgrade the jekyll version to 3.9, it works and happy jekylling!

**Comment by andradeoromulo** [comment]
Yes, that's what I've done to get it running. However, I just thought it would be a great idea to change the dependency in the theme to use the latest stable version of jekyll. Thanks for the help tho :)
